geekshop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view, name='user_create'),
    path('users/read/', adminapp.UserListView.as_view, name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view, name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path, re_path
from . import views

app_name = 'authapp'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', views.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path
from . import views

app_name = 'basketapp'

urlpatterns = [
    path("", views.view, name="view"),
    path("add/<int:product_id/>", views.add, name="add"),
    path("remove/<int:basket_item_id>/", views.remove, name="remove"),
    path("edit/<int:basket_item_id>/<int:quantity>/", views.edit, name="edit"),
]

geekshop/geekshop/urls.py
from os import name
from xml.dom.minidom import Document
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import authapp

from mainapp import views as mainapp


urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path("admin/", admin.site.urls),
    path("", mainapp.index, name="main"),
    path("contact/", mainapp.contact, name="contact"),
    path("products/", include("mainapp.urls", namespace="products")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("basket/", include("basketapp.urls", namespace="basket")),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('social_django.urls', namespace='social')),
    path("orders/", include("ordersapp.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path("", views.products, name="main"),
    path("<int:category_id>", views.category, name="category"),
    path("<int:category_id/<int:page>", views.category, name="page_category"),
    path("product/int:product_id>", views.product, name="product"),

]

geekshop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import path

app_name="ordersapp"

urlpatterns = [
   path('', ordersapp.OrderList.as_view(), name='orders_list'),
   path('forming/complete/<int:pk>/',
           ordersapp.order_forming_complete, name='order_forming_complete'),
   path('create/', ordersapp.OrderCreate.as_view(),
           name='order_create'),
   path('read/<int:pk>/', ordersapp.OrderDetail.as_view(),
           name='order_read'),
   path('update/<int:pk>/', ordersapp.OrderUpdate.as_view(),
           name='order_update'),
   path('delete/<int:pk>/', ordersapp.OrderDelete.as_view(),
           name='order_delete'),
   path('product/<int:pk>/price/', ordersapp.product_price, name='product_price'),

]

geekshop/mainapp/models.py
from pyexpat import model
from tabnanny import verbose
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=100)
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return self.name

class ProductManager(models.Manager):

    def active_items(self):
        return Product.objects.filter(is_active=True)

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField (verbose_name='имя', max_length=100)
    price = models.DecimalField(verbose_name='цена', max_digits=7, decimal_places=2, default=0, db_index=True)
    color = models.PositiveIntegerField(verbose_name='цвет', default=0x000000)
    description = models.TextField(verbose_name='описание', blank=True)
    image = models.ImageField(verbose_name='картинка', blank=True, upload_to='products')
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0, db_index=True)
    is_active = models.BooleanField(verbose_name='активный', default=True, db_index=True)

    objects = ProductManager()

    def __str__(self):
        return self.name
   

geekshop/mainapp/views.py
import random
from functools import lru_cache
from django.core.cache import cache
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage
from django.views.decorators.cache import cache_page
from .models import Product, ProductCategory





def index(request):
    products = Product.objects.all()[:4]
    return render(
        request, 
        "mainapp/index.html", 
        context={
        "title":"Главная",
        "products": products, 
        },
    )

def get_hot_product(queryset):
    return random.choice(queryset)

def get_categories():
    if settings.LOW_CACHE:
        KEY = 'all_categories'
        categories = cache.get(KEY)
        if not categories:
            categories = ProductCategory.objects.all()
            cache.set(KEY, categories)
        return categories 
    else:
        return ProductCategory.objects.all()

def products(request):
    categories = get_categories()
    products = Product.objects.all()
    hot_product = get_hot_product(products)

    return render(
        request, 
        'mainapp/products.html', 
        context={
        'title':'Продукты',
        'products':products.exclude(pk=hot_product.pk)[:4],
        'hot_product': hot_product,
        'categories': categories, 
        },
    )

@lru_cache
def get_products(category_id):
    return Product.objects.filter(category_id=category_id)


def category(request, category_id, page=1):
    categories = ProductCategory.objects.all()
    category = get_object_or_404(ProductCategory, id=category_id)
    products = get_products(category_id)
    hot_product = get_hot_product(products)
    paginator = Paginator(products.exclude(pk=hot_product.pk), 3)
    try:
        products_page = paginator.page(page)
    except EmptyPage:
        products_page = paginator.page(paginator.num_pages)


    return render(
        request, 
        'mainapp/products.html', 
        context={
            'title':'Продукты',
            'products': products_page,
            'hot_product': get_hot_product(products),
            'paginator': paginator,
            'page': products_page,
            'category' : category,
            'categories': categories, 
        },
    )


def product(request, product_id):
    products = get_object_or_404(Product, pk=product_id)
    categories = ProductCategory.objects.all()
    return render(
        request, 
        'mainapp/product.html', 
        context={
        'title':'Продукты',
        'product': product,
        'categories': categories, 
        },
    )

@cache_page(3600)
def contact(request):
    return render(
        request, 
        "mainapp/contact.html", 
        context={
        'title':'Контакты',
        },
    )

geekshop/mainapp/templates/mainapp/includes/inc_categories_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li><a href="{% url 'products:main' %}" 
            class="{% if request.resolver_mutch.view_name == 'products:main' %} active {% endif %}"
            >все</a></li>
        {% for c in categories %}
        <li><a href="{% url 'products:category' c.id %}" 
            class="{% if request.resolver_mutch.view_name in ['products:category', 'products.product'] and request.resolver_mutch.kwargs.category_id == category.id %} 
            active 
            {% endif %}"
        >{{ c.name }}</a></li>
        {% endfor %}
    </ul>
</div>

geekshop/mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="{% url 'main' %}" class="logo"></a>
<ul class="menu">
    {% for link in menu_links %}
    <li>
        <a href="{% url link.url %}" 
            {% if request.resolver_match.view_name in link.active %}
                class="active"
            {% endif %}
        >
            {{link.name}}
        </a>
    </li>
    {% endfor %}
    <li>
        <a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
            контакты
        </a>
     </li>
    {% if user.is_authenticated %}
    <li>
        <div class="dropdown">
            <a class="dropdown-toggle" href="" data-toggle="dropdown">
                {{ user.first_name|default:'Пользователь' }}
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li>
                    <a href="{% url 'auth:edit' %}">
                        профиль
                    </a>
                </li>
                <li>
                    <a href="{% url 'ordersapp:orders_list' %}">
                        заказы
                    </a>
                </li>
            </ul>
        </div>
    </li>
 
    {% if user.is_superuser %}
    <li>
        <a href="{% url 'admin:users' %}">
            Админка
        </a>
    </li>
    {% endif %}
    <li>
        <a href="{% url 'basket:view' %}">
            <i class="fa fa-shopping-basket"></i>
            {{ user.basket.total_cost }} руб. ({{ user.basket.total_quantity }})
        </a>
    </li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">Выйти</a>
        {% else %}
            <a href="{% url 'auth:login' %}">Войти</a>
        {% endif %}
    </li>
</ul>
<a href="#" class="search"></a>
<a href="#" class="basket"></a>

geekshop/mainapp/templates/mainapp/includes/inc_products.html
{% if paginator %}
    {% if page.has_previous %}
        <a href="{% url 'products:page_category' category.id page.previous_page_number %}"> Назад </a>
    {% endif %}

    Страница {{ page.number }} из {{ paginator.num_pages }}

    {% if page.has_next %}
        <a href="{% url 'products:page_category' category.id page.next_page_number %}"> Вперёд </a> 
    {% endif %}
{% endif %}
{% for product in products %}
<div class="block">
    {% with product_category=product.category %}
    <a href="{% url 'products:product' product.id %}"><img src= {% /media/{{ product.image }}  %} alt="">
        <div class="text">
            <img src="/static/img/icon-hover.png" alt="">
            <h4>{{ product.name }}</h4>
            <h5>{{ product_category }}</h5>
            <p>{{ product.description }}</p>
        </div>
    </a>
    {% endwith %}
</div>
{% endfor %}